apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: canary-tutorial-app
  namespace: canary-tutorial
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - canary-tutorial
  selector:
    matchLabels:
      app: canary-tutorial-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: kubernetes_pod_name
        - sourceLabels: [__meta_kubernetes_pod_label_role]
          targetLabel: role
