apiVersion: v1
kind: Service
metadata:
  name: canary-tutorial-app-canary
  namespace: canary-tutorial
  labels:
    app: canary-tutorial-app
    role: canary
spec:
  selector:
    app: canary-tutorial-app
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
